services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"   # Web UI
      - "7687:7687"   # Bolt protocol (app connections)
    environment:
      - NEO4J_AUTH=neo4j/12345678  # user: neo4j  password: 12345678
      - NEO4J_PLUGINS=["apoc"]     # APOC plugin
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/data:/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/logs:/logs
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/neo4j/conf:/conf
    restart: unless-stopped